build daily with updates submodules

diff --git a/.github/workflows/rebuild.yml b/.github/workflows/rebuild.yml
--- a/.github/workflows/rebuild.yml
+++ b/.github/workflows/rebuild.yml
@@ -11,20 +11,26 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+    - name: checkout
+      uses: actions/checkout@v2
+      with:
+        token: ${{ secrets.CI_TOKEN }}
+        submodules: true
 
-      - name: Set Git Config
-        run: |
-          git config --global user.name "GitHub Actions"
-          git config --global user.email "actions@github.com"
+    - name: update submodules
+      run: |
+        git pull --recurse-submodules
+        git submodule update --remote --recursive
 
-      - name: Create empty commit to trigger rebuild
-        run: |
-          git commit --allow-empty -m "Trigger rebuild"
-
-      - name: Push changes
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gebruik het ingebouwde GitHub-token
-        run: |
-          git push origin HEAD
+    - name: commit updates
+      run: |
+        git config --global user.name 'Git bot'
+        git config --global user.email 'bot@noreply.github.com'
+        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
+        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
+        
+#      - name: Trigger GitHub pages rebuild
+#        run: |
+#          curl --fail --request POST \
+#            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
+#            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
